apiVersion: v1
kind: ConfigMap
metadata:
  name: pharma-config
  namespace: pharma-ai
data:
  APP_ENV: "production"
  APP_LOG_LEVEL: "INFO"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-service:4317"
  RAG_VECTOR_STORE: "azure_ai_search"
